### ISSUE TITLE
Handle is invalid error in Windows

### ISSUE THREAD

**Issue by seabamirum** [sbenten/d3MapRenderer#13]
It doesn't seem to matter what parameters I use, the plugin fails with the following error after pressing OK.

An error has occured while executing Python code: 

WindowsError: [Error 6] The handle is invalid 
Traceback (most recent call last):
  File "C:/Users/xcx6/.qgis2/python/plugins\d3MapRenderer\d3_Map.py", line 593, in performOutput
    raise e
WindowsError: [Error 6] The handle is invalid

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.12.3-Lyon Lyon, 99ac688 

Python Path:
C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISLY~1/apps/qgis/./python

**Comment by sbenten** [comment]
Yes, that will be a result of the plugin finding the registry key
HKEY_CURRENT_USER\Software\Node.js\InstallPath,
but there being no actual value present.

Please see my response to #11

**Comment by sbenten** [comment]
Yes, I can replicate that with an empty registry key for the InstallPath.
The latest checkins on the master branch have added the ability to use GeoJson rather than TopoJson as a workaround for some of the dependency issues that have been reported. Functionality of the web page will not differ between the two Json formats.
Give the master branch a try with the GeoJson format.
